spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.withub.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles: dev
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6335el0f44z138b0o.mysql.rds.aliyuncs.com:3306/springcloud
    username: root
    password: qz041012
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true #服务发现开关
    service-url: #客户端(服务提供者)注册到哪一个Eureka Server服务注册中心,多个用逗号分隔
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径可以显示IP地址
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.withub.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles: prod
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6335el0f44z138b0o.mysql.rds.aliyuncs.com:3306/springcloud2
    username: root
    password: qz041012
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true #服务发现开关
    service-url: #客户端(服务提供者)注册到哪一个Eureka Server服务注册中心,多个用逗号分隔
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径可以显示IP地址